@startuml
actor ATCC as ATCC
participant "System" as Sys


ATCC -> Sys: Authenticate User
Sys --> ATCC: Authentication Successful

ATCC -> Sys: Register Aircraft
Sys --> Sys: Verify Model is in Catalog
Sys --> ATCC: Inform Successful Register

@enduml