POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "technician",
  "password": "technician123"
}


###

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0OGU5YjkxYi1kNzEyLTQzZmMtODZiZS1jZTlkNTY5NWRhNmIiLCJyb2xlcyI6WyJNQUlOVEVOQU5DRV9URUNITklDSUFOIl0sImlhdCI6MTc4MTk1OTI2NiwiZXhwIjoxNzgxOTYyODY2fQ.d4dR2yih47j_K87D_CyubI8U_4KGEdH0Bv8zepmVOLY


GET http://localhost:8081/api/maintenance/records?aircraft=CS-TUA&attribute=AIRFRAME&initialDate=2026-06-10
Content-Type: application/json
Authorization: Bearer {{token}}



