POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "technician",
  "password": "technician123"
}


###

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyODE3Mzg1OS0yMjEwLTQzNjctODExMy1kZjAwMWIzZGRjZjIiLCJyb2xlcyI6WyJNQUlOVEVOQU5DRV9URUNITklDSUFOIl0sImlhdCI6MTc4MjAwMDcwNywiZXhwIjoxNzgyMDA0MzA3fQ.EuD4i8abR3LuzePThzj2JLWo816lMh2nKgqhMeDkDXg



GET http://localhost:8081/api/maintenance/records?aircraft=CS-TUA&attribute=AIRFRAME&initialDate=2026-06-10
Content-Type: application/json
Authorization: Bearer {{token}}



