@startuml
skinparam monochrome true
skinparam shadowing false

title System Sequence Diagram (SSD) - US115

actor "Maintenance Technician" as User
participant "System" as System

activate User


User -> System : Authenticate User
activate System
System --> User : Authentication Successful (Token JWT)
deactivate System

User -> System : createMaintenanceTemplate(name, type, aircraftModels, checklist)
activate System


System --> User : Inform Success (201 Created + Template Data)
System --> User : Error (400 Bad Request)
deactivate System

deactivate User
@endif