POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxYmUyOGQyZS0xNGFiLTRkZjgtODQ3Zi01NTU2ZDA0MGFlYWQiLCJyb2xlcyI6WyJCQUNLT0ZGSUNFIl0sImlhdCI6MTc4MTM2NTQwMywiZXhwIjoxNzgxMzY5MDAzfQ.f-gyBtF1SMdAv1INsKVc-ohhlLa-qksGvxIxcuCl1GQ


POST http://localhost:8081/api/catalog/model
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelName": "A320",
  "manufacturer": "Airbus",
  "modelImage": [
    "https://example.com/images/a320-front.jpg",
    "https://example.com/images/a320-side.jpg"
  ],
  "specs": {
    "fuelCapacityLiters": 24210,
    "maximumRangeKm": 6150,
    "cruisingSpeedKph": 840,
    "standardSeatingCapacity": 180
  }
}

