POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTZhNWU2ZC1kNmQxLTRkNDktYjczMy05YjQzMWJmMTI0NjEiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTM2NTQ0OCwiZXhwIjoxNzgxMzY5MDQ4fQ.kcgtF6Ia4TFIRzjazahhNJ6_Fv5VET9YtdeGF6N1qfU


###
POST http://localhost:8081/api/hangar/aircraft
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "registrationNumber": "CS-TU",
  "modelName": "A320",
  "manufacturingDate": "2025-06-15",
  "totalOperationalHours": 12450.5,
  "totalFlightHours": 11890.0,
  "availability": "AVAILABLE"
}