POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}


###
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZDc1ZmEzNi1kYTZiLTQxYmEtYTA5Zi0xODQxYTA4NzAzOTEiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTk5Mjc4OCwiZXhwIjoxNzgxOTk2Mzg4fQ.BQLjI8YfEc8Fus4-UvkeF28_JEdvMgLmJIogacvUyxM



GET http://localhost:8081/api/hangar/analytics/aircraft-availability
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:8081/api/hangar/analytics/status-summary
Content-Type: application/json
Authorization: Bearer {{token}}

###
@registrationNumber=D-ABXA
GET http://localhost:8081/api/hangar/aircraft/{{registrationNumber}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

