POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

###

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MjgwYTdhOS03YTgzLTQ2ZjMtODBkNi02MzYwN2RlNjk1YTciLCJyb2xlcyI6WyJCQUNLT0ZGSUNFIl0sImlhdCI6MTc4MTY5MzM3OCwiZXhwIjoxNzgxNjk2OTc4fQ.Y2vaCAhsOXq0w9xXnk3vUCEHkn08chGlzUCbYTRV6pg


GET http://localhost:8081/api/catalog/rankings?mode=assignments
Content-Type: application/json
Authorization: Bearer {{token}}0


###
GET http://localhost:8081/api/catalog/rankings?mode=flight-hours
Content-Type: application/json
Authorization: Bearer {{token}}