POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

###

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2OGMxMjg2ZS05YjE5LTRlZTYtOWYyYy04OTQ5NGZiMGY2ZDQiLCJyb2xlcyI6WyJCQUNLT0ZGSUNFIl0sImlhdCI6MTc4MTQ4MTY0MiwiZXhwIjoxNzgxNDg1MjQyfQ.gUg7IxNOH-qXAJoKk6x3fCCAjewgRqeOVZ604IZoeq8

GET http://localhost:8081/api/catalog/rankings?mode=assignments
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:8081/api/catalog/rankings?mode=flight-hours
Content-Type: application/json
Authorization: Bearer {{token}}