POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "technician",
  "password": "technician123"
}

###
@id=1
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyODE3Mzg1OS0yMjEwLTQzNjctODExMy1kZjAwMWIzZGRjZjIiLCJyb2xlcyI6WyJNQUlOVEVOQU5DRV9URUNITklDSUFOIl0sImlhdCI6MTc4MjAwMDY2NywiZXhwIjoxNzgyMDA0MjY3fQ.KWfnoawllJfnrdvYWhSt750o84qJSrHMQueJjcqWRrg


GET http://localhost:8081/api/maintenance/records/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
PATCH http://localhost:8081/api/maintenance/records/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "attribute": "AIRFRAME"
}