POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1YzcyMGE1OS1mOTg5LTRhNjYtOTNlZS1lYzJlMWMwYzE4OTUiLCJyb2xlcyI6WyJCQUNLT0ZGSUNFIl0sImlhdCI6MTc3OTYzMzkxOCwiZXhwIjoxNzc5NjM3NTE4fQ.PiGj3wf16J7o6uTCrrxkC8HixE-PeYBB2aCb73U2WOQ

POST http://localhost:8081/api/catalog/model
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelName": "A320",
  "manufacturer": "Airbus",
  "modelImage": [
    "https://example.com/images/a320-front.jpg",
    "https://example.com/images/a320-side.jpg"
  ],
  "specs": {
    "fuelCapacityLiters": 24210,
    "maximumRangeKm": 6150,
    "cruisingSpeedKph": 840,
    "standardSeatingCapacity": 180
  }
}

