POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "backoffice123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ZDFiYmEwYi0xYzE1LTRkYzgtYjJmZS1hNGYzYmQ2YjhlMmUiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE3NzkwNDE5ODMsImV4cCI6MTc3OTA0NTU4M30.r8a6SqqAnupAJY3Ed4-XC-isH0EkjR0xXokwryz_YSo

POST http://localhost:8081/api/catalog/model
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelName": "A320",
  "manufacturer": "Airbus",
  "modelImage": [
    "https://example.com/images/a320-front.jpg",
    "https://example.com/images/a320-side.jpg"
  ],
  "specs": {
    "fuelCapacityLiters": 24210,
    "maximumRangeKm": 6150,
    "cruisingSpeedKph": 840,
    "standardSeatingCapacity": 180
  }
}

