POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3MjQ1YThiOC0xM2Y5LTRkMjgtYmMwOC1hYWRkMGFlNGY0NmMiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MjAwMDU3NiwiZXhwIjoxNzgyMDA0MTc2fQ.MziY0IWNGbl22puAgjL_MV6nilKtLcbY5Ls4sPYHGIc


GET http://localhost:8081/api/hangar/analytics/fuel-efficiency
Content-Type: application/json
Authorization: Bearer {{token}}



