@startuml
skinparam classAttributeIconSize 0
hide empty members
skinparam packageStyle frame

' AIRPORT AGGREGATE

package "Aggregate: Airport" <<Frame>> {

class Airport <<aggregate root>> {
    - iataCode: String <<id>>
    - airportType: String
    - name: String
    - status: AirportStatus
    - contacts: List<Contact>
    - facilities: Facilities
    - airportLocation: AirportLocation
    - routeDistance: Double
    - airportRunways: List<Runway>
    - airportPhotos: List<String>
    + addRunway(runway: Runway)
    + removeRunway(runwayId: String)
    + addPhotos(photosUri: List<String>)
    + updatePhotos(photosUri: List<String>)
    + updateFacilities(facilities: Facilities)
    + addCertification(certification: Certification)
    + removeCertification(name: String)
    + updateStatus(status: AirportStatus)
    + isOperationalForFlight(onDate: Date): Boolean
}

class Runway <<entity>> {
    - runwayId: Long <<id>>
    - runwayName: String
    - length: Double
    - orientation: String
    - status: RunwayStatus
}

class AirportLocation <<value object>> {
    - city: String
    - country: String
    - timezone: String
    - region: String
    - latitude: Double
    - longitude: Double
}

class Facilities <<value object>> {
    - terminalCount: Integer
    - gateCount: Integer
    - services: List<String>
}

class Contact <<value object>> {
    - type: ContactType
    - value: String
}

class Certification <<entity>> {
    - name: String
    - category: String
    - startsAt: Date
    - expiresAt: Date
}

enum AirportStatus {
    OPERATIONAL
    CLOSED
    UNDER_MAINTENANCE
}

enum RunwayStatus {
    OPEN
    IN_USE
    UNDER_MAINTENANCE
}

enum ContactType {
    PHONE
    EMAIL
    FAX
    SOCIAL_NETWORK
}

Airport *-- "0..*" Runway
Airport "1"--"1" AirportLocation
Airport *-- Facilities
Airport *-- "0..*" Contact
Airport *-- "0..*" Certification
}

' FLIGHT AGGREGATE

package "Aggregate: Flight" <<Frame>> {

class Flight <<aggregate root>> {
    - flightId: Long <<id>>
    - flightStatus : FlightStatus
    - routeId: Long <<ref>>
    - aircraftId: String <<ref>>
    - scheduledDeparture: DateTime
    - scheduledArrival: DateTime
  }

enum FlightStatus {
    DELAYED
    SCHEDULED
    DEPARTED
    CANCELED
    ARRIVED
}
}

' ROUTE AGGREGATE

package "Aggregate: Route" <<Frame>> {

class Route <<aggregate root>> {
    - routeId: Long <<id>>
    - status: RouteStatus
    - originIataCode: String <<ref>>
    - destinationIataCode: String <<ref>>
    - routeHistory: RouteHistory
    - estimatedFlightTime: Double
    - type: RouteType
    + testRoute()
    + addRoute()
    + deactivateRoute()
    + updateRoute()
}

class RouteHistory <<value object>>{
    - routeBegin: Date
    - routeFinish: Date
    - routeUsage: Integer
    +updateRouteUsage(usage: Integer)
}

class RouteRequirements <<value object>> {
    - requiredRange: Double
    - requiredCapacity: Integer
}

enum RouteStatus {
    ACTIVE
    INACTIVE
    ARCHIVED
}

enum RouteType{
    DIRECT
    SCALED
}

Route *-- RouteRequirements
Route "1"--"1" RouteHistory
}

' AIRCRAFT MODEL AGGREGATE

package "Aggregate: AircraftCatalog" <<Frame>> {

class AircraftModel <<aggregate root>> {
    - modelId: String <<id>>
    - modelName: String
    - modelImage: List <String>
    - manufacturer: String
    + setupModelImages(imagesURI: List<String>)
}

class AircraftSpecs <<value object>> {
    - fuelCapacityLiters: Double
    - maximumRangeKm: Double
    - cruisingSpeedKph: Double
    - updateAircraftSpecs()
}

AircraftModel *-- AircraftSpecs
}

' AIRCRAFT AGGREGATE

package "Aggregate: Aircraft" <<Frame>> {

class Aircraft <<aggregate root>> {
    - registrationNumber: String <<id>>
    - modelId: String <<ref>>
    - manufacturingDate: Date
    - features: List<String>
    - totalOperationalHours: Double
    - totalFlightHours: Double
    - meanRange: Double
    + updateOperationHours(hours: Double)
    + updateFlightHours(hours: Double)
    + recordFlight(distance: Double, hours: Double)
    + updateMeanRange(traveledDistance: Double)
    + updateSeatingCapacity(hours: Integer)
    + updateStatus(status: AircraftAvailability)
}

class SeatingPack <<value object>>{
    - seatingCapacity: Integer
    - seatingOrientation: String
}

class InstalledComponent <<entity>> {
    - serialNumber: String <<id>>
    - partNumber: String <<ref>>
    - status: String
}

class AircraftCertification <<entity>> {
    - aircraftCertificationId: Long
    - name: String
    - category: String
    - startAt: LocalDate
    - expiresAt: LocalDate
}

enum AircraftAvailability {
    AVAILABLE
    IN_FLIGHT
    MAINTENANCE
    INACTIVE
}

Aircraft *-- "0..*" InstalledComponent
Aircraft *-- "0..*" AircraftCertification
Aircraft *-- "1..*" SeatingPack

}


' MAINTENANCE AGGREGATE

package "Aggregate: Maintenance" <<Frame>> {

class MaintenanceRecord <<aggregate root>> {
    - recordId: Long  <<id>>
    - aircraftRegistrationNumber: String <<ref>>
    - templateId: Long
    - description: String
    - technicians: List <collaboratorId>
    - supervisor: String <collaboratorId>
    - startDate: LocalDate
    - endDate: LocalDate
    - usedParts: usedParts
    - duration: Double
    - doneList:DoneList
    - status: MaintenanceStatus
    + updateDuration(realDuration: Double)
    + markAsCompleted(notes: String)
}

class MaintenanceTemplate <<entity>> {
    - templateId: Long <<id>>
    - name: String
    - expectedDuration: Double
    - templateChecklist: Map<String,Boolean>
    - attribute: MaintenanceAttribute
    - operation: MaintenanceType
}

class DoneList <<value object>>{
    - tasksDone: Map<String,Boolean>
    - completionNotes: String
}

enum MaintenanceType {
    INSPECTION
    SCHEDULED
    OVERHAUL
    MODIFICATION
}

enum MaintenanceStatus {
    ONGOING
    COMPLETED
}

enum MaintenanceAttribute {
    ENGINE
    AIRFRAME
    AVIONICS
    INTERIOR
    EXTERIOR
}


class UsedPart <<value object>> {
    - partSerialNumber: String
    - quantity: Integer
    - price: Double
}
MaintenanceRecord *-- "1" MaintenanceTemplate
MaintenanceRecord *-- "1..*" UsedPart
MaintenanceRecord *-- "1" DoneList
}

package "Aggregate: Users" <<Frame>> {
class Technician <<entity>> {
}

class Supervisor <<entity>> {
}

class Collaborator <<entity>> {
    - pk: Long
    - collaboratorId: UUID
    - username: String
    - password: String
    - email: String
}

Technician *--"1..1" Collaborator
Supervisor *--"1..1" Collaborator
}

' RELATIONSHIPS

Flight --> Route : routeId <<ref>>
Flight --> Aircraft : aircraftId <<ref>>
Aircraft --> AircraftModel : modelId <<ref>>
Route --> Airport : IATA codes <<ref>>
MaintenanceRecord --> Aircraft : aircraftRegistrationNumber <<ref>>
Collaborator --> MaintenanceRecord : collaboratorId <<ref>>
@enduml