@startuml
skinparam monochrome true
skinparam shadowing false

title Sequence Diagram: US116 - Log Maintenance Activity

actor "Maintenance Technician" as User
participant ":AuthController" as Auth
participant ":MaintenanceController" as Ctrl
participant ":MaintenanceService" as Service
participant ":AircraftRepository" as RepoAircraft
participant ":MaintenanceTemplateRepository" as RepoTemplate
participant "activity:MaintenanceActivity" as Activity <<Aggregate Root>>
participant ":MaintenanceActivityRepository" as RepoActivity

activate User


User -> Auth : Authenticate User
activate Auth
Auth --> User : Authentication Successful (Token JWT)
deactivate Auth


User -> Ctrl : logMaintenanceActivity(aircraftReg, templateId, date, technicians, status, notes)
activate Ctrl

Ctrl -> Service : logActivity(aircraftReg, templateId, date, technicians, status, notes)
activate Service

    Service -> RepoAircraft : findByRegistration(aircraftReg)
    activate RepoAircraft
    RepoAircraft --> Service : aircraft
    deactivate RepoAircraft

    Service -> RepoTemplate : findById(templateId)
    activate RepoTemplate
    RepoTemplate --> Service : template
    deactivate RepoTemplate


    Service -> Activity** : <<create>> (aircraft, template, date, technicians, status, notes)

    Service -> RepoActivity : save(activity)
    activate RepoActivity
    RepoActivity --> Service : savedActivity
    deactivate RepoActivity

    Service --> Ctrl : maintenanceActivityDTO / Error

    Ctrl --> User : Success (201 Created + Links)
    Ctrl --> User : Error (400 Bad Request / 404 Not Found)

deactivate Service
deactivate Ctrl
deactivate User
@enduml