POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOTZhNWU2ZC1kNmQxLTRkNDktYjczMy05YjQzMWJmMTI0NjEiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTM2NTQ3MiwiZXhwIjoxNzgxMzY5MDcyfQ.WQn8Ak658q-DxtD0YorHAH-zlq_QdaAOcFBDP4wJluI


###
GET http://localhost:8081/api/hangar/aircraft?model=A320&status=MAINTENANCE
Authorization: Bearer {{token}}