POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhNGJjNGJmYi04NzU2LTRmY2UtYTEyOC0zMmVjYjc2NTY1OTEiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTY5Njg1NiwiZXhwIjoxNzgxNzAwNDU2fQ.xum-4uZ8koIYCX77LmOv-gZwgTZaJQ-fxNDx_fuRvmc


###
GET http://localhost:8081/api/hangar/aircraft?model=A320&status=MAINTENANCE
Authorization: Bearer {{token}}