POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@registrationNumber = CS-TUA

@token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5YTViYzFmNC0yYjc4LTQ3ZGUtOTllNy04NDhiM2FiOGNlMTYiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTQ4MjM0MiwiZXhwIjoxNzgxNDg1OTQyfQ.n5K7Ujsl5u3IMUGW_3jUEdilzFxYzqC5s2sSlA8ZCb0


GET http://localhost:8081/api/hangar/aircraft/{{registrationNumber}}/compatible-routes
Content-Type: application/json
Authorization: Bearer {{token}}
