POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "atcc",
  "password": "atcc123"
}

###
@registrationNumber = CS-TUA

@token =eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzODJkYjQ2Ni1lMGRjLTQ3MTQtYjUxZi0wYjJhZmZlOWVjOGYiLCJyb2xlcyI6WyJBVENDIl0sImlhdCI6MTc4MTY5MzQ0NywiZXhwIjoxNzgxNjk3MDQ3fQ.mGyn_0tGqR1e7cTt5CNRF1ysYWM8rQrdhrRaFacKep0


GET http://localhost:8081/api/hangar/aircraft/{{registrationNumber}}/compatible-routes
Content-Type: application/json
Authorization: Bearer {{token}}
